name: double_tap_player_view
description: A new Flutter plugin.
version: 0.0.1
authors:
  - Daichi Furiya <hiroyuktamura@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.2
  after_layout: ^1.0.7+2
  uuid: 2.2.2
  freezed_annotation: ^0.12.0
  circular_reveal_animation: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  freezed: ^0.12.2
  build_runner: ^1.10.4

flutter:
  plugin:
    platforms:
      android:
        package: com.cks.double_tap_player_view
        pluginClass: DoubleTapPlayerViewPlugin
      ios:
        pluginClass: DoubleTapPlayerViewPlugin
