name: double_tap_player_view
description: A new Flutter plugin.
version: 0.0.1
authors:
  - Daichi Furiya <hiroyuktamura@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cks.double_tap_player_view
        pluginClass: DoubleTapPlayerViewPlugin
      ios:
        pluginClass: DoubleTapPlayerViewPlugin
