name: double_tap_player_view
description: a widget to handle fast forward/rewind behavior by double tap and horizontal drag like a video player.
version: 1.0.6
homepage: https://github.com/HiroyukTamura/double_tap_player_view
repository: https://github.com/HiroyukTamura/double_tap_player_view

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.0-nullsafety.3
  uuid: ^3.0.0
  freezed_annotation: ^0.13.0-nullsafety.0
  circular_reveal_animation: ^2.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  freezed: ^0.13.0-nullsafety.2
  build_runner: ^1.11.5